In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
from numpy import genfromtxt
my_data = genfromtxt('cryo.csv', delimiter=',')

In [5]:
my_data

array([[      nan,       nan,       nan,       nan,       nan,       nan,
              nan],
       [1.000e+00, 3.500e+01, 1.200e+01, 5.000e+00, 1.000e+00, 1.000e+02,
        0.000e+00],
       [1.000e+00, 2.900e+01, 7.000e+00, 5.000e+00, 1.000e+00, 9.600e+01,
        1.000e+00],
       [1.000e+00, 5.000e+01, 8.000e+00, 1.000e+00, 3.000e+00, 1.320e+02,
        0.000e+00],
       [1.000e+00, 3.200e+01, 1.175e+01, 7.000e+00, 3.000e+00, 7.500e+02,
        0.000e+00],
       [1.000e+00, 6.700e+01, 9.250e+00, 1.000e+00, 1.000e+00, 4.200e+01,
        0.000e+00],
       [1.000e+00, 4.100e+01, 8.000e+00, 2.000e+00, 2.000e+00, 2.000e+01,
        1.000e+00],
       [1.000e+00, 3.600e+01, 1.100e+01, 2.000e+00, 1.000e+00, 8.000e+00,
        0.000e+00],
       [1.000e+00, 5.900e+01, 3.500e+00, 3.000e+00, 3.000e+00, 2.000e+01,
        0.000e+00],
       [1.000e+00, 2.000e+01, 4.500e+00, 1.200e+01, 1.000e+00, 6.000e+00,
        1.000e+00],
       [2.000e+00, 3.400e+01, 1.125e+01, 3.000e+00, 3.000e+00, 1.500e+02,
        0.000e+00],
       [2.000e+00, 2.100e+01, 1.075e+01, 5.000e+00, 1.000e+00, 3.500e+01,
        0.000e+00],
       [2.000e+00, 1.500e+01, 6.000e+00, 2.000e+00, 1.000e+00, 3.000e+01,
        1.000e+00],
       [2.000e+00, 1.500e+01, 2.000e+00, 3.000e+00, 1.000e+00, 4.000e+00,
        1.000e+00],
       [2.000e+00, 1.500e+01, 3.750e+00, 2.000e+00, 3.000e+00, 7.000e+01,
        1.000e+00],
       [2.000e+00, 1.700e+01, 1.100e+01, 2.000e+00, 1.000e+00, 1.000e+01,
        0.000e+00],
       [2.000e+00, 1.700e+01, 5.250e+00, 3.000e+00, 1.000e+00, 6.300e+01,
        1.000e+00],
       [2.000e+00, 2.300e+01, 1.175e+01, 1.200e+01, 3.000e+00, 7.200e+01,
        0.000e+00],
       [2.000e+00, 2.700e+01, 8.750e+00, 2.000e+00, 1.000e+00, 6.000e+00,
        0.000e+00],
       [2.000e+00, 1.500e+01, 4.250e+00, 1.000e+00, 1.000e+00, 6.000e+00,
        1.000e+00],
       [2.000e+00, 1.800e+01, 5.750e+00, 1.000e+00, 1.000e+00, 8.000e+01,
        1.000e+00],
       [1.000e+00, 2.200e+01, 5.500e+00, 2.000e+00, 1.000e+00, 7.000e+01,
        1.000e+00],
       [2.000e+00, 1.600e+01, 8.500e+00, 1.000e+00, 2.000e+00, 6.000e+01,
        1.000e+00],
       [1.000e+00, 2.800e+01, 4.750e+00, 3.000e+00, 1.000e+00, 1.000e+02,
        1.000e+00],
       [2.000e+00, 4.000e+01, 9.750e+00, 1.000e+00, 2.000e+00, 8.000e+01,
        0.000e+00],
       [1.000e+00, 3.000e+01, 2.500e+00, 2.000e+00, 1.000e+00, 1.150e+02,
        1.000e+00],
       [2.000e+00, 3.400e+01, 1.200e+01, 3.000e+00, 3.000e+00, 9.500e+01,
        0.000e+00],
       [1.000e+00, 2.000e+01, 5.000e-01, 2.000e+00, 1.000e+00, 7.500e+01,
        1.000e+00],
       [2.000e+00, 3.500e+01, 1.200e+01, 5.000e+00, 3.000e+00, 1.000e+02,
        0.000e+00],
       [2.000e+00, 2.400e+01, 9.500e+00, 3.000e+00, 3.000e+00, 2.000e+01,
        0.000e+00],
       [2.000e+00, 1.900e+01, 8.750e+00, 6.000e+00, 1.000e+00, 1.600e+02,
        1.000e+00],
       [1.000e+00, 3.500e+01, 9.250e+00, 9.000e+00, 1.000e+00, 1.000e+02,
        1.000e+00],
       [1.000e+00, 2.900e+01, 7.250e+00, 6.000e+00, 1.000e+00, 9.600e+01,
        1.000e+00],
       [1.000e+00, 5.000e+01, 8.750e+00, 1.100e+01, 3.000e+00, 1.320e+02,
        0.000e+00],
       [2.000e+00, 3.200e+01, 1.200e+01, 4.000e+00, 3.000e+00, 7.500e+02,
        0.000e+00],
       [2.000e+00, 6.700e+01, 1.200e+01, 1.200e+01, 3.000e+00, 4.200e+01,
        0.000e+00],
       [2.000e+00, 4.100e+01, 1.050e+01, 2.000e+00, 2.000e+00, 2.000e+01,
        1.000e+00],
       [2.000e+00, 3.600e+01, 1.100e+01, 6.000e+00, 1.000e+00, 8.000e+00,
        0.000e+00],
       [1.000e+00, 6.300e+01, 2.750e+00, 3.000e+00, 3.000e+00, 2.000e+01,
        0.000e+00],
       [1.000e+00, 2.000e+01, 5.000e+00, 3.000e+00, 1.000e+00, 6.000e+00,
        1.000e+00],
       [1.000e+00, 3.400e+01, 1.200e+01, 1.000e+00, 3.000e+00, 1.500e+02,
        0.000e+00],
       [2.000e+00, 2.100e+01, 1.050e+01, 5.000e+00, 1.000e+00, 3.500e+01,
        0.000e+00],
       [2.000e+00, 1.500e+01, 8.000e+00, 1.200e+01, 1.000e+00, 3.000e+01,
        1.000e+00],
       [1.000e+00, 1.500e+01, 3.500e+00, 2.000e+00, 1.000e+00, 4.000e+00,
        1.000e+00],
       [2.000e+00, 1.500e+01, 1.500e+00, 1.200e+01, 3.000e+00, 7.000e+01,
        1.000e+00],
       [1.000e+00, 1.700e+01, 1.150e+01, 2.000e+00, 1.000e+00, 1.000e+01,
        0.000e+00],
       [1.000e+00, 1.700e+01, 5.250e+00, 4.000e+00, 1.000e+00, 6.300e+01,
        1.000e+00],
       [2.000e+00, 2.300e+01, 9.500e+00, 5.000e+00, 3.000e+00, 7.200e+01,
        0.000e+00],
       [1.000e+00, 2.700e+01, 1.000e+01, 5.000e+00, 1.000e+00, 6.000e+00,
        0.000e+00],
       [1.000e+00, 1.500e+01, 4.000e+00, 7.000e+00, 1.000e+00, 6.000e+00,
        1.000e+00],
       [2.000e+00, 1.800e+01, 4.500e+00, 8.000e+00, 1.000e+00, 8.000e+01,
        1.000e+00],
       [2.000e+00, 2.200e+01, 5.000e+00, 9.000e+00, 1.000e+00, 7.000e+01,
        1.000e+00],
       [1.000e+00, 1.600e+01, 1.025e+01, 3.000e+00, 2.000e+00, 6.000e+01,
        1.000e+00],
       [2.000e+00, 2.800e+01, 4.000e+00, 1.100e+01, 1.000e+00, 1.000e+02,
        1.000e+00],
       [2.000e+00, 4.000e+01, 8.750e+00, 6.000e+00, 2.000e+00, 8.000e+01,
        0.000e+00],
       [2.000e+00, 3.000e+01, 5.000e-01, 8.000e+00, 3.000e+00, 1.150e+02,
        1.000e+00],
       [1.000e+00, 3.400e+01, 1.075e+01, 1.000e+00, 3.000e+00, 9.500e+01,
        0.000e+00],
       [1.000e+00, 2.000e+01, 3.750e+00, 1.100e+01, 1.000e+00, 7.500e+01,
        1.000e+00],
       [2.000e+00, 3.500e+01, 8.500e+00, 6.000e+00, 3.000e+00, 1.000e+02,
        0.000e+00],
       [1.000e+00, 2.400e+01, 9.500e+00, 8.000e+00, 1.000e+00, 2.000e+01,
        1.000e+00],
       [2.000e+00, 1.900e+01, 8.000e+00, 9.000e+00, 1.000e+00, 1.600e+02,
        1.000e+00],
       [1.000e+00, 3.500e+01, 7.250e+00, 2.000e+00, 1.000e+00, 1.000e+02,
        1.000e+00],
       [1.000e+00, 2.900e+01, 1.175e+01, 5.000e+00, 1.000e+00, 9.600e+01,
        0.000e+00],
       [2.000e+00, 5.000e+01, 9.500e+00, 4.000e+00, 3.000e+00, 1.320e+02,
        0.000e+00],
       [2.000e+00, 3.200e+01, 1.200e+01, 1.200e+01, 3.000e+00, 7.500e+02,
        0.000e+00],
       [1.000e+00, 6.700e+01, 1.000e+01, 7.000e+00, 1.000e+00, 4.200e+01,
        0.000e+00],
       [2.000e+00, 4.100e+01, 7.750e+00, 5.000e+00, 2.000e+00, 2.000e+01,
        1.000e+00],
       [2.000e+00, 3.600e+01, 1.050e+01, 4.000e+00, 1.000e+00, 8.000e+00,
        0.000e+00],
       [1.000e+00, 6.700e+01, 3.750e+00, 1.100e+01, 3.000e+00, 2.000e+01,
        0.000e+00],
       [1.000e+00, 2.000e+01, 4.000e+00, 3.000e+00, 1.000e+00, 6.000e+00,
        1.000e+00],
       [1.000e+00, 3.400e+01, 1.125e+01, 1.000e+00, 3.000e+00, 1.500e+02,
        0.000e+00],
       [2.000e+00, 2.100e+01, 1.075e+01, 7.000e+00, 1.000e+00, 3.500e+01,
        0.000e+00],
       [1.000e+00, 1.500e+01, 1.050e+01, 1.100e+01, 1.000e+00, 3.000e+01,
        1.000e+00],
       [1.000e+00, 1.500e+01, 2.000e+00, 1.100e+01, 1.000e+00, 4.000e+00,
        1.000e+00],
       [2.000e+00, 1.500e+01, 2.000e+00, 1.000e+01, 3.000e+00, 7.000e+01,
        1.000e+00],
       [1.000e+00, 1.700e+01, 9.250e+00, 1.200e+01, 1.000e+00, 1.000e+01,
        0.000e+00],
       [1.000e+00, 1.700e+01, 5.750e+00, 1.000e+01, 1.000e+00, 6.300e+01,
        1.000e+00],
       [1.000e+00, 2.300e+01, 1.025e+01, 7.000e+00, 3.000e+00, 7.200e+01,
        0.000e+00],
       [1.000e+00, 2.700e+01, 1.050e+01, 7.000e+00, 1.000e+00, 6.000e+00,
        0.000e+00],
       [1.000e+00, 1.500e+01, 5.500e+00, 5.000e+00, 1.000e+00, 6.000e+00,
        1.000e+00],
       [1.000e+00, 1.800e+01, 4.000e+00, 1.000e+00, 1.000e+00, 8.000e+01,
        1.000e+00],
       [2.000e+00, 2.200e+01, 4.500e+00, 2.000e+00, 1.000e+00, 7.000e+01,
        1.000e+00],
       [1.000e+00, 1.600e+01, 1.100e+01, 3.000e+00, 2.000e+00, 6.000e+01,
        1.000e+00],
       [2.000e+00, 2.800e+01, 5.000e+00, 9.000e+00, 1.000e+00, 1.000e+02,
        1.000e+00],
       [1.000e+00, 4.000e+01, 1.150e+01, 9.000e+00, 2.000e+00, 8.000e+01,
        0.000e+00],
       [1.000e+00, 3.000e+01, 2.500e-01, 1.000e+01, 1.000e+00, 1.150e+02,
        1.000e+00],
       [2.000e+00, 3.400e+01, 1.200e+01, 3.000e+00, 3.000e+00, 9.500e+01,
        0.000e+00],
       [2.000e+00, 2.000e+01, 3.500e+00, 6.000e+00, 1.000e+00, 7.500e+01,
        1.000e+00],
       [2.000e+00, 3.500e+01, 8.250e+00, 8.000e+00, 3.000e+00, 1.000e+02,
        0.000e+00],
       [1.000e+00, 2.400e+01, 1.075e+01, 1.000e+01, 1.000e+00, 2.000e+01,
        1.000e+00],
       [1.000e+00, 1.900e+01, 8.000e+00, 8.000e+00, 1.000e+00, 1.600e+02,
        1.000e+00]])

In [23]:
column_names = ["sex","age","Time","Number_of_Warts","Type","Area","Result_of_Treatment"]

data = pd.read_csv('cryo.csv')
y = data["Result_of_Treatment"]
data.drop(columns=["Result_of_Treatment"])

    sex  age   Time  Number_of_Warts  Type  Area
0     1   35  12.00                5     1   100
1     1   29   7.00                5     1    96
2     1   50   8.00                1     3   132
3     1   32  11.75                7     3   750
4     1   67   9.25                1     1    42
5     1   41   8.00                2     2    20
6     1   36  11.00                2     1     8
7     1   59   3.50                3     3    20
8     1   20   4.50               12     1     6
9     2   34  11.25                3     3   150
10    2   21  10.75                5     1    35
11    2   15   6.00                2     1    30
12    2   15   2.00                3     1     4
13    2   15   3.75                2     3    70
14    2   17  11.00                2     1    10
15    2   17   5.25                3     1    63
16    2   23  11.75               12     3    72
17    2   27   8.75                2     1     6
18    2   15   4.25                1     1     6
19    2   18   5.75                1     1    80
20    1   22   5.50                2     1    70
21    2   16   8.50                1     2    60
22    1   28   4.75                3     1   100
23    2   40   9.75                1     2    80
24    1   30   2.50                2     1   115
25    2   34  12.00                3     3    95
26    1   20   0.50                2     1    75
27    2   35  12.00                5     3   100
28    2   24   9.50                3     3    20
29    2   19   8.75                6     1   160
..  ...  ...    ...              ...   ...   ...
60    1   35   7.25                2     1   100
61    1   29  11.75                5     1    96
62    2   50   9.50                4     3   132
63    2   32  12.00               12     3   750
64    1   67  10.00                7     1    42
65    2   41   7.75                5     2    20
66    2   36  10.50                4     1     8
67    1   67   3.75               11     3    20
68    1   20   4.00                3     1     6
69    1   34  11.25                1     3   150
70    2   21  10.75                7     1    35
71    1   15  10.50               11     1    30
72    1   15   2.00               11     1     4
73    2   15   2.00               10     3    70
74    1   17   9.25               12     1    10
75    1   17   5.75               10     1    63
76    1   23  10.25                7     3    72
77    1   27  10.50                7     1     6
78    1   15   5.50                5     1     6
79    1   18   4.00                1     1    80
80    2   22   4.50                2     1    70
81    1   16  11.00                3     2    60
82    2   28   5.00                9     1   100
83    1   40  11.50                9     2    80
84    1   30   0.25               10     1   115
85    2   34  12.00                3     3    95
86    2   20   3.50                6     1    75
87    2   35   8.25                8     3   100
88    1   24  10.75               10     1    20
89    1   19   8.00                8     1   160

[90 rows x 6 columns]

In [24]:
data

    sex  age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0     1   35  12.00                5     1   100                    0
1     1   29   7.00                5     1    96                    1
2     1   50   8.00                1     3   132                    0
3     1   32  11.75                7     3   750                    0
4     1   67   9.25                1     1    42                    0
5     1   41   8.00                2     2    20                    1
6     1   36  11.00                2     1     8                    0
7     1   59   3.50                3     3    20                    0
8     1   20   4.50               12     1     6                    1
9     2   34  11.25                3     3   150                    0
10    2   21  10.75                5     1    35                    0
11    2   15   6.00                2     1    30                    1
12    2   15   2.00                3     1     4                    1
13    2   15   3.75                2     3    70                    1
14    2   17  11.00                2     1    10                    0
15    2   17   5.25                3     1    63                    1
16    2   23  11.75               12     3    72                    0
17    2   27   8.75                2     1     6                    0
18    2   15   4.25                1     1     6                    1
19    2   18   5.75                1     1    80                    1
20    1   22   5.50                2     1    70                    1
21    2   16   8.50                1     2    60                    1
22    1   28   4.75                3     1   100                    1
23    2   40   9.75                1     2    80                    0
24    1   30   2.50                2     1   115                    1
25    2   34  12.00                3     3    95                    0
26    1   20   0.50                2     1    75                    1
27    2   35  12.00                5     3   100                    0
28    2   24   9.50                3     3    20                    0
29    2   19   8.75                6     1   160                    1
..  ...  ...    ...              ...   ...   ...                  ...
60    1   35   7.25                2     1   100                    1
61    1   29  11.75                5     1    96                    0
62    2   50   9.50                4     3   132                    0
63    2   32  12.00               12     3   750                    0
64    1   67  10.00                7     1    42                    0
65    2   41   7.75                5     2    20                    1
66    2   36  10.50                4     1     8                    0
67    1   67   3.75               11     3    20                    0
68    1   20   4.00                3     1     6                    1
69    1   34  11.25                1     3   150                    0
70    2   21  10.75                7     1    35                    0
71    1   15  10.50               11     1    30                    1
72    1   15   2.00               11     1     4                    1
73    2   15   2.00               10     3    70                    1
74    1   17   9.25               12     1    10                    0
75    1   17   5.75               10     1    63                    1
76    1   23  10.25                7     3    72                    0
77    1   27  10.50                7     1     6                    0
78    1   15   5.50                5     1     6                    1
79    1   18   4.00                1     1    80                    1
80    2   22   4.50                2     1    70                    1
81    1   16  11.00                3     2    60                    1
82    2   28   5.00                9     1   100                    1
83    1   40  11.50                9     2    80                    0
84    1   30   0.25               10     1   115                    1
85    2   34  12.00                3     3    95                    0
86    2   20   3.50                6     1    75                    1
87    2   35   8.25                8     3   100                    0
88    1   24  10.75               10     1    20                    1
89    1   19   8.00                8     1   160                    1

[90 rows x 7 columns]

In [14]:
import tensorflow as tf

/Users/lusenii/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

In [22]:
data=tf.convert_to_tensor(data)
y = tf.convert_to_tensor(y)

In [16]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split(data, y, test_size=0.33, random_state=42)